import express from 'express';
import cors from 'cors';
import path from 'path';
import env from './config/env';
import prisma from './config/db';
import { errorHandler } from './middleware/errorHandler';
import publicServicesRoutes from './routes/public/services';
import publicCitiesRoutes from './routes/public/cities';
import publicFaqRoutes from './routes/public/faq';
import publicTestimonialsRoutes from './routes/public/testimonials';
import publicPagesRoutes from './routes/public/pages';
import publicFooterRoutes from './routes/public/footer';
import publicContactRoutes from './routes/public/contact';
import publicCompanionRoutes from './routes/public/companion';
import publicSiteSettingsRoutes from './routes/public/siteSettings';
import publicThemeRoutes from './routes/public/theme';
import publicHeroRoutes from './routes/public/hero';
import publicHowItWorksRoutes from './routes/public/howItWorks';
import publicCustomerAuthRoutes from './routes/public/customerAuth';
import publicCustomerMeRoutes from './routes/public/customerMe';
import publicExperiencesRoutes from './routes/public/experiences';
import publicCompanionRequestsRoutes from './routes/public/companionRequests';
import publicCompanionAvailabilityRoutes from './routes/public/companionAvailability';
import publicBookingsRoutes from './routes/public/bookings';
import publicPaymentsRoutes from './routes/public/payments';
import publicCompanionProfilesRoutes from './routes/public/companionProfiles';
import adminAuthRoutes from './routes/admin/auth';
import adminDashboardRoutes from './routes/admin/dashboard';
import adminInquiriesRoutes from './routes/admin/inquiries';
import adminCompanionsRoutes from './routes/admin/companions';
import adminPagesRoutes from './routes/admin/pages';
import adminFooterRoutes from './routes/admin/footer';
import adminSocialLinksRoutes from './routes/admin/socialLinks';
import adminHowItWorksRoutes from './routes/admin/howItWorks';
import adminServicesRoutes from './routes/admin/services';
import adminFaqRoutes from './routes/admin/faq';
import adminTestimonialsRoutes from './routes/admin/testimonials';
import adminCitiesRoutes from './routes/admin/cities';
import adminThemeRoutes from './routes/admin/theme';
import adminHeroRoutes from './routes/admin/hero';
import adminSiteSettingsRoutes from './routes/admin/siteSettings';
import adminMediaRoutes from './routes/admin/media';

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));
app.use('/api/v1/public/site-settings', publicSiteSettingsRoutes);
app.use('/api/v1/public/theme', publicThemeRoutes);
app.use('/api/v1/public/hero-slides', publicHeroRoutes);
app.use('/api/v1/public/services', publicServicesRoutes);
app.use('/api/v1/public/cities', publicCitiesRoutes);
app.use('/api/v1/public/experiences', publicExperiencesRoutes);
app.use('/api/v1/public/companion-requests', publicCompanionRequestsRoutes);
app.use('/api/v1/public/companion-availability', publicCompanionAvailabilityRoutes);
app.use('/api/v1/public/bookings', publicBookingsRoutes);
app.use('/api/v1/public/payments', publicPaymentsRoutes);
app.use('/api/v1/public/companions', publicCompanionProfilesRoutes);
app.use('/api/v1/public/faq', publicFaqRoutes);
app.use('/api/v1/public/testimonials', publicTestimonialsRoutes);
app.use('/api/v1/public/pages', publicPagesRoutes);
app.use('/api/v1/public/footer', publicFooterRoutes);
app.use('/api/v1/public/how-it-works', publicHowItWorksRoutes);
app.use('/api/v1/public/contact', publicContactRoutes);
app.use('/api/v1/public/companion-application', publicCompanionRoutes);
app.use('/api/v1/public/auth', publicCustomerAuthRoutes);
app.use('/api/v1/public/me', publicCustomerMeRoutes);
app.use('/api/v1/admin/auth', adminAuthRoutes);
app.use('/api/v1/admin/dashboard', adminDashboardRoutes);
app.use('/api/v1/admin/media', adminMediaRoutes);
app.use('/api/v1/admin/site-settings', adminSiteSettingsRoutes);
app.use('/api/v1/admin/theme', adminThemeRoutes);
app.use('/api/v1/admin/hero-slides', adminHeroRoutes);
app.use('/api/v1/admin/services', adminServicesRoutes);
app.use('/api/v1/admin/faq', adminFaqRoutes);
app.use('/api/v1/admin/testimonials', adminTestimonialsRoutes);
app.use('/api/v1/admin/cities', adminCitiesRoutes);
app.use('/api/v1/admin/pages', adminPagesRoutes);
app.use('/api/v1/admin/footer', adminFooterRoutes);
app.use('/api/v1/admin/social-links', adminSocialLinksRoutes);
app.use('/api/v1/admin/inquiries', adminInquiriesRoutes);
app.use('/api/v1/admin/companions', adminCompanionsRoutes);
app.use('/api/v1/admin/how-it-works', adminHowItWorksRoutes);
app.get('/api/v1/health', (_req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use((_req, res) => res.status(404).json({ success: false, error: { message: 'Route not found' } }));
app.use(errorHandler);
if (env.NODE_ENV !== 'test') {
  const startServer = async () => { try { await prisma.$connect(); console.log('PostgreSQL connected via Prisma'); } catch (error) { console.error('Database connection error:', error); process.exit(1); } app.listen(env.PORT, () => console.log(`Server running on port ${env.PORT} in ${env.NODE_ENV} mode`)); };
  startServer();
  const shutdown = async () => { await prisma.$disconnect(); process.exit(0); };
  process.on('SIGINT', shutdown); process.on('SIGTERM', shutdown);
}
export default app;
